### ISSUE TITLE
this break the tool

### ISSUE THREAD

**Issue by kevindevm** [xanthics/poe_fractured#1]
Rarity: Rare
    Kraken Beam
    Military Staff
    --------
    Staff
    Physical Damage: 59-142 (augmented)
    Elemental Damage: 12-21 (augmented)
    Critical Strike Chance: 6.40%
    Attacks per Second: 1.20
    Weapon Range: 11
    --------
    Requirements:
    Level: 45
    Str: 78
    Int: 78
    --------
    Sockets: B-R 
    --------
    Item Level: 71
    --------
    +18% Chance to Block Attack Damage while wielding a Staff
    --------
    Adds 19 to 40 Fire Damage to Spells (fractured)
    Adds 25 to 41 Physical Damage
    Adds 12 to 21 Cold Damage
    65% increased Critical Strike Chance for Spells
    --------
    Fractured Item

**Comment by xanthics** [comment]
Use version 0.1 for now.  I broke some things after migrating to repoe that I didn't notice until I was headed to bed.  Working on them now.

**Comment by xanthics** [comment]
5148112c2a21ae781c7f258210c8caeb90cf561a
